# Блок для Let's Encrypt верификации (порт 80, специальный путь)
server {
    listen 80;
    server_name domain.com; # ← ваш домен

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Блок для Let's Encrypt верификации (субдомен 3x-ui)
server {
    listen 80;
    server_name panel.domain.com;  # ← ваш субдомен

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Блок для HTTPS
server {
    listen 443 ssl;
    server_name domain.com;

    ssl_certificate     /etc/nginx/certs/key/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/key/privkey.pem;  

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# HTTPS для панели 3x-ui
server {
    listen 443 ssl;
    server_name panel.domain.com;  # ← ваш субдомен для 3x-ui

    ssl_certificate     /etc/nginx/certs/panel/fullchain.pem;  # ← отдельная папка
    ssl_certificate_key /etc/nginx/certs/panel/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://ваш_айпи_адрес:2043;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # Важно для WebSocket и длинных соединений
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
